"""empty message

Revision ID: a480b4a11fd4
Revises: 8920dbfd8f59
Create Date: 2022-06-22 14:09:43.956137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a480b4a11fd4'
down_revision = '8920dbfd8f59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userbites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bite_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bite_id'], ['bite.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'bite_id')
    )
    op.drop_table('user_bites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_bites',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bite_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bite_id'], ['bite.id'], name='user_bites_bite_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_bites_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'bite_id', name='user_bites_pkey')
    )
    op.drop_table('userbites')
    # ### end Alembic commands ###
